console.log(true && true)
console.log(false && true)
console.log(true || true)
console.log(true || false)
console.log(false || false)
console.log(!true)
console.log(!false)
console.log(true || false && true)
console.log(true && false || true && false)
console.log(5 <= 6 && 5 > 4)
console.log(5 <= 6 && 5 > 7)
console.log(5 <= 6 || 5 > 7)
console.log(5 <= 6 || 5 > 7 && 5 !== 3)
console.log(5 <= 7 && !(5 !== 3))